# syntax=docker/dockerfile:1

# ─── Build ────────────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app

ARG DEEPL_API_KEY
ARG EXPO_PUBLIC_SUPABASE_ANON_KEY
ARG EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG EXPO_PUBLIC_VAPI_PUBLIC_KEY
ARG EXPO_PUBLIC_VAPI_ASSISTANT_ID
ARG EXPO_PUBLIC_ELEVENLABS_API_KEY
ARG EXPO_PUBLIC_ELEVENLABS_VOICE_ID

ENV DEEPL_API_KEY=$DEEPL_API_KEY
ENV EXPO_PUBLIC_SUPABASE_ANON_KEY=$EXPO_PUBLIC_SUPABASE_ANON_KEY
ENV EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY=$EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV EXPO_PUBLIC_VAPI_PUBLIC_KEY=$EXPO_PUBLIC_VAPI_PUBLIC_KEY
ENV EXPO_PUBLIC_VAPI_ASSISTANT_ID=$EXPO_PUBLIC_VAPI_ASSISTANT_ID
ENV EXPO_PUBLIC_ELEVENLABS_API_KEY=$EXPO_PUBLIC_ELEVENLABS_API_KEY
ENV EXPO_PUBLIC_ELEVENLABS_VOICE_ID=$EXPO_PUBLIC_ELEVENLABS_VOICE_ID

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .
RUN npx expo export --platform web

# ─── Serve ────────────────────────────────────────────────────────────────────
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
